baseURL = 'https://netherlands-coding-live.github.io'
languageCode = 'en-us'
title = 'NL_CL | Netherlands Coding Live'
theme = 'hugo-theme-console'
enableEmoji = true
summaryLength = 20
buildFuture = true

[params]
  custom_css = [ "css/customstyle.css" ]
  titleCutting = true

  [[params.navlinks]]
  name = "events/"
  url = "events/"

  [[params.navlinks]]
  name = "photos/"
  url = "photos/"

  [[params.navlinks]]
  name = "community/"
  url = "community/"

  [[params.navlinks]]
  name = "works/"
  url = "works/"

[mediaTypes]
  [mediaTypes.'text/calendar']
    suffixes = ['ics']

[outputFormats]
  [outputFormats.calendar]
    baseName = 'calendar'
    isPlainText = true
    mediaType = 'text/calendar'
    permalinkable = true
    protocol = 'webcal://'

[outputs]
  home = ["HTML", "ics"]
  section = ["HTML", "Calendar"]
  page = ["HTML", "rss",]
  list = ["HTML", "rss",]
  event = ["HTML", "rss", "Calendar"]